### ISSUE TITLE
Logo update

### ISSUE THREAD

**Issue by jelv** [matthijsvdr/Tweakers.bundle#4]
Since april this year Tweakers is using a [new logo](https://tweakers.net/plan/843/tweakers-tweakt-logo-nieuw-logo-voor-hetzelfde-tweakers.html). It would be great if the Channel can be updated with the new logo just like they use on [tweakers-dev](https://github.com/tweakers-dev). The logo can be downloaded [here on the right](https://tweakers.net/info/over_tweakers/Logo-Tweakers).

**Comment by matthijsvdr** [comment]
Updated the icons with the new tweakers logo, see https://github.com/matthijsvdr/Tweakers.bundle/commit/7be09982b06e7d4aa7a2db85cde34ccce2c2ef9a
